package deepseek

import (
	"fmt"
	"strings"

	"github.com/featuresignals/server/internal/janitor/codeanalysis"
)

// BuildAnalysisPrompt creates the prompt for analyzing flag references.
func BuildAnalysisPrompt(req codeanalysis.AnalyzeRequest) string {
	var fileSections strings.Builder
	totalFiles := len(req.Files)
	fileIdx := 0

	for path, content := range req.Files {
		fileIdx++
		lines := strings.Split(string(content), "\n")
		lineRange := fmt.Sprintf("1-%d", len(lines))

		lang := req.Language
		if lang == "" {
			lang = detectLanguage(path)
		}

		fileSections.WriteString(fmt.Sprintf("\nFILE %d/%d: %s (lines %s)\n", fileIdx, totalFiles, path, lineRange))
		fileSections.WriteString(fmt.Sprintf("LANGUAGE: %s\n\n", lang))
		fileSections.WriteString("```" + lang + "\n")
		fileSections.Write(content)
		fileSections.WriteString("\n```\n")
	}

	prompt := fmt.Sprintf(`You are a senior software engineer analyzing code to safely remove a stale feature flag.

CONTEXT:
- Flag key: "%s"
- Flag name: "%s"
- This flag has been serving 100%% %s for %d days across all environments
- We need to remove the flag condition and keep the %s branch's code inline
- There are %d files containing references to this flag

%s

For every reference to "%s" in this code:
1. Identify the exact line number
2. Determine the reference type (evaluation call, conditional, pass-through, etc.)
3. If it's in a conditional: what is the structure (if/else, if-only, ternary, switch)? Which branch should be kept?
4. Is it safe to remove this reference?
5. Provide the exact cleaned code snippet after removal

Respond ONLY with valid JSON:
{
  "references": [
    {
      "line": <number>,
      "reference_type": "evaluation" | "conditional" | "pass_through" | "logging",
      "safe_to_remove": true | false,
      "keep_branch": "true_branch" | "false_branch" | "both" | "neither",
      "reason": "<concise explanation>",
      "cleaned_snippet": "<exact code after removal>"
    }
  ],
  "overall_safe": true | false,
  "confidence": 0.0-1.0,
  "notes": "<any important observations>"
}`,
		req.FlagKey, req.FlagName, req.TrueBranch, req.DaysServed, req.TrueBranch,
		totalFiles, fileSections.String(), req.FlagKey)

	return prompt
}

// BuildPRDescriptionPrompt creates the prompt for generating a PR description.
func BuildPRDescriptionPrompt(flagKey, flagName string, changes []codeanalysis.FileChange) string {
	var changesDesc strings.Builder
	for _, c := range changes {
		mode := c.Mode
		if mode == "" {
			mode = "modify"
		}
		changesDesc.WriteString(fmt.Sprintf("- %s: %s\n", mode, c.Path))
	}

	prompt := fmt.Sprintf(`Generate a pull request description for removing the stale feature flag "%s" ("%s").

Files modified:
%s

The PR was generated by an automated janitor tool. Include:
1. A clear PR title
2. Summary of what was removed and why
3. List of files changed
4. A warning that this is AI-generated and needs manual review

Respond ONLY with valid JSON:
{
  "title": "<PR title>",
  "description": "<PR description body>"
}`, flagKey, flagName, changesDesc.String())

	return prompt
}

// BuildValidationPrompt creates the prompt for validating cleaned code.
func BuildValidationPrompt(req codeanalysis.ValidateRequest) string {
	prompt := fmt.Sprintf(`Compare these two code versions for semantic equivalence.

The feature flag "%s" is being removed because it has been serving 100%% %s. The %s branch's code should be preserved inline.

ORIGINAL (contains flag check):
%s

CLEANED (flag removed, %s branch preserved):
%s

Is the cleaned version semantically equivalent to the original when the flag is %s?
Ignore formatting changes, whitespace differences, or cosmetic differences.
Only flag actual semantic differences that would change behavior.

Respond ONLY with valid JSON:
{
  "valid": true | false,
  "confidence": 0.0-1.0,
  "issues": ["<description of each issue>"]
}`,
		req.FlagKey, req.ActiveBranch, req.ActiveBranch,
		string(req.OriginalCode),
		req.ActiveBranch, string(req.CleanedCode),
		req.ActiveBranch)

	return prompt
}

// detectLanguage attempts to detect the programming language from a file path.
func detectLanguage(path string) string {
	path = strings.ToLower(path)
	switch {
	case strings.HasSuffix(path, ".go"):
		return "go"
	case strings.HasSuffix(path, ".ts"), strings.HasSuffix(path, ".tsx"):
		return "typescript"
	case strings.HasSuffix(path, ".js"), strings.HasSuffix(path, ".jsx"):
		return "javascript"
	case strings.HasSuffix(path, ".py"):
		return "python"
	case strings.HasSuffix(path, ".java"):
		return "java"
	case strings.HasSuffix(path, ".rb"):
		return "ruby"
	case strings.HasSuffix(path, ".cs"):
		return "csharp"
	case strings.HasSuffix(path, ".php"):
		return "php"
	case strings.HasSuffix(path, ".swift"):
		return "swift"
	case strings.HasSuffix(path, ".kt"), strings.HasSuffix(path, ".kts"):
		return "kotlin"
	case strings.HasSuffix(path, ".rs"):
		return "rust"
	case strings.HasSuffix(path, ".scala"):
		return "scala"
	default:
		return "text"
	}
}