package openai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"time"

	"github.com/featuresignals/server/internal/janitor/codeanalysis"
)

const (
	defaultModel     = "gpt-4o-mini"
	defaultBaseURL   = "https://api.openai.com/v1"
	defaultTimeout   = 60 * time.Second
	defaultMaxTokens = 4096
)

// OpenAIProvider implements CodeAnalysisProvider using an OpenAI-compatible API.
// This works with OpenAI, Azure OpenAI, Ollama, vLLM, TGI, and any other
// OpenAI-compatible endpoint.
type OpenAIProvider struct {
	apiKey      string
	model       string
	baseURL     string
	client      *http.Client
	logger      *slog.Logger
	temperature float64
	maxTokens   int
}

// NewOpenAIProvider creates a new OpenAI-compatible provider.
func NewOpenAIProvider(config codeanalysis.ProviderConfig) (codeanalysis.CodeAnalysisProvider, error) {
	baseURL := config.BaseURL
	if baseURL == "" {
		baseURL = defaultBaseURL
	}
	model := config.Model
	if model == "" {
		model = defaultModel
	}
	timeout := config.Timeout
	if timeout <= 0 {
		timeout = defaultTimeout
	}
	maxTokens := config.MaxTokens
	if maxTokens <= 0 {
		maxTokens = defaultMaxTokens
	}
	temp := config.Temperature
	if temp == 0 {
		temp = 0.1
	}

	return &OpenAIProvider{
		apiKey:      config.APIKey,
		model:       model,
		baseURL:     baseURL,
		client:      &http.Client{Timeout: timeout},
		logger:      slog.With("provider", "openai-compatible", "model", model),
		temperature: temp,
		maxTokens:   maxTokens,
	}, nil
}

func (p *OpenAIProvider) Name() string { return "openai-compatible" }

// ─── Request/Response Types ─────────────────────────────────────────────

type chatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type chatRequest struct {
	Model          string          `json:"model"`
	Messages       []chatMessage   `json:"messages"`
	Temperature    float64         `json:"temperature"`
	MaxTokens      int             `json:"max_tokens"`
	ResponseFormat *responseFormat `json:"response_format,omitempty"`
}

type responseFormat struct {
	Type string `json:"type"`
}

type chatResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
	Usage *struct {
		PromptTokens     int `json:"prompt_tokens"`
		CompletionTokens int `json:"completion_tokens"`
		TotalTokens      int `json:"total_tokens"`
	} `json:"usage,omitempty"`
	Error *struct {
		Message string `json:"message"`
		Type    string `json:"type"`
		Code    string `json:"code,omitempty"`
	} `json:"error,omitempty"`
}

// ─── Interface Methods ──────────────────────────────────────────────────

func (p *OpenAIProvider) AnalyzeFlagReferences(ctx context.Context, req codeanalysis.AnalyzeRequest) (*codeanalysis.AnalyzeResponse, error) {
	prompt := buildAnalysisPrompt(req)
	resp, err := p.callLLM(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("openai analyze: %w", err)
	}

	var result analysisResult
	if err := json.Unmarshal([]byte(resp), &result); err != nil {
		return nil, fmt.Errorf("openai parse analysis response: %w", err)
	}

	response := &codeanalysis.AnalyzeResponse{
		OverallSafe: result.OverallSafe,
		Confidence:  result.Confidence,
		Summary:     result.Notes,
		Files:       make([]codeanalysis.FileAnalysisResult, 0),
		TokenUsage:  codeanalysis.TokenUsage{},
	}

	for _, ref := range result.References {
		refType := ref.ReferenceType
		if refType == "" {
			refType = "conditional"
		}
		keepBranch := ref.KeepBranch
		if keepBranch == "" {
			keepBranch = "true_branch"
		}

		response.Files = append(response.Files, codeanalysis.FileAnalysisResult{
			FilePath: req.FlagKey + ".analyzed",
			Safe:     ref.SafeToRemove,
			References: []codeanalysis.FlagReferenceAnalysis{{
				Line:          ref.Line,
				Column:        ref.Column,
				ReferenceType: refType,
				SafeToRemove:  ref.SafeToRemove,
				KeepBranch:    keepBranch,
				Reason:        ref.Reason,
			}},
			Issues: []string{},
		})
	}

	return response, nil
}

func (p *OpenAIProvider) GeneratePRDescription(ctx context.Context, flagKey, flagName string, changes []codeanalysis.FileChange) (string, error) {
	var changesDesc string
	for _, c := range changes {
		mode := c.Mode
		if mode == "" {
			mode = "modify"
		}
		changesDesc += fmt.Sprintf("- %s: %s\n", mode, c.Path)
	}

	prompt := fmt.Sprintf(`Generate a pull request description for removing stale feature flag "%s" ("%s").

Files modified:
%s

The PR was generated by an automated tool. Include title, summary, file list, and a manual review warning.

Respond ONLY with valid JSON:
{"title": "<PR title>", "description": "<PR description body>"}`, flagKey, flagName, changesDesc)

	resp, err := p.callLLM(ctx, prompt)
	if err != nil {
		return "", fmt.Errorf("openai generate pr: %w", err)
	}

	var result struct {
		Title       string `json:"title"`
		Description string `json:"description"`
	}
	if err := json.Unmarshal([]byte(resp), &result); err != nil {
		return resp, nil
	}
	return result.Title + "\n\n" + result.Description, nil
}

func (p *OpenAIProvider) ValidateCleanup(ctx context.Context, req codeanalysis.ValidateRequest) (*codeanalysis.ValidateResponse, error) {
	prompt := fmt.Sprintf(`Compare these two code versions for semantic equivalence.

The feature flag "%s" is being removed. The %s branch's code should be preserved.

ORIGINAL:
%s

CLEANED:
%s

Is the cleaned version semantically equivalent? Respond ONLY with valid JSON:
{"valid": true|false, "confidence": 0.0-1.0, "issues": ["..."]}`,
		req.FlagKey, req.ActiveBranch, string(req.OriginalCode), string(req.CleanedCode))

	resp, err := p.callLLM(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("openai validate: %w", err)
	}

	var result struct {
		Valid      bool     `json:"valid"`
		Confidence float64  `json:"confidence"`
		Issues     []string `json:"issues"`
	}
	if err := json.Unmarshal([]byte(resp), &result); err != nil {
		return nil, fmt.Errorf("openai parse validation: %w", err)
	}

	return &codeanalysis.ValidateResponse{
		Valid:      result.Valid,
		Confidence: result.Confidence,
		Issues:     result.Issues,
	}, nil
}

// ─── Internal ───────────────────────────────────────────────────────────

func (p *OpenAIProvider) callLLM(ctx context.Context, prompt string) (string, error) {
	reqBody := chatRequest{
		Model:       p.model,
		Temperature: p.temperature,
		MaxTokens:   p.maxTokens,
		ResponseFormat: &responseFormat{Type: "json_object"},
		Messages: []chatMessage{
			{Role: "system", Content: "You are a senior software engineer analyzing code to safely remove stale feature flags. Respond with valid JSON only."},
			{Role: "user", Content: prompt},
		},
	}

	bodyBytes, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, p.baseURL+"/chat/completions", bytes.NewReader(bodyBytes))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	// OpenAI uses Bearer auth, Azure OpenAI uses api-key header
	// We try Bearer first, and if apiKey looks like an Azure key (starts with a number), use api-key
	if len(p.apiKey) > 0 && p.apiKey[0] >= '0' && p.apiKey[0] <= '9' {
		httpReq.Header.Set("api-key", p.apiKey)
	} else {
		httpReq.Header.Set("Authorization", "Bearer "+p.apiKey)
	}

	resp, err := p.client.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("http call: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		var errResp chatResponse
		if json.Unmarshal(respBody, &errResp) == nil && errResp.Error != nil {
			return "", fmt.Errorf("API error (status %d): %s", resp.StatusCode, errResp.Error.Message)
		}
		return "", fmt.Errorf("API error (status %d): %s", resp.StatusCode, string(respBody))
	}

	var chatResp chatResponse
	if err := json.Unmarshal(respBody, &chatResp); err != nil {
		return "", fmt.Errorf("parse response: %w", err)
	}

	if len(chatResp.Choices) == 0 {
		return "", fmt.Errorf("no choices in response")
	}

	return chatResp.Choices[0].Message.Content, nil
}

// ─── Response Types ─────────────────────────────────────────────────────

type analysisResult struct {
	References []struct {
		Line           int     `json:"line"`
		Column         int     `json:"column"`
		ReferenceType  string  `json:"reference_type"`
		SafeToRemove   bool    `json:"safe_to_remove"`
		KeepBranch     string  `json:"keep_branch"`
		Reason         string  `json:"reason"`
		CleanedSnippet string  `json:"cleaned_snippet"`
	} `json:"references"`
	OverallSafe bool    `json:"overall_safe"`
	Confidence  float64 `json:"confidence"`
	Notes       string  `json:"notes"`
}

// buildAnalysisPrompt creates the analysis prompt (reused from deepseek pattern).
func buildAnalysisPrompt(req codeanalysis.AnalyzeRequest) string {
	var fileSections string
	totalFiles := len(req.Files)

	for path, content := range req.Files {
		lang := "text"
		fileSections += fmt.Sprintf("\nFILE: %s\nLANGUAGE: %s\n\n```%s\n%s\n```\n", path, lang, lang, string(content))
	}

	return fmt.Sprintf(`You are a senior software engineer analyzing code to safely remove a stale feature flag.

CONTEXT:
- Flag key: "%s"
- Flag name: "%s"
- This flag has been serving 100%% %s for %d days
- We need to remove the flag condition and keep the %s branch's code inline
- There are %d files containing references

%s

For every reference to "%s" in this code, identify line number, reference type, safe removal status, and provide cleaned code.

Respond ONLY with valid JSON:
{
  "references": [{"line": <number>, "reference_type": "conditional"|"evaluation"|"pass_through"|"logging", "safe_to_remove": true|false, "keep_branch": "true_branch"|"false_branch"|"both"|"neither", "reason": "...", "cleaned_snippet": "..."}],
  "overall_safe": true|false,
  "confidence": 0.0-1.0,
  "notes": "..."
}`,
		req.FlagKey, req.FlagName, req.TrueBranch, req.DaysServed, req.TrueBranch,
		totalFiles, fileSections, req.FlagKey)
}

// Register adds the OpenAI-compatible provider to the given registry.
func Register(r *codeanalysis.ProviderRegistry) error {
	return r.Register("openai-compatible", NewOpenAIProvider, codeanalysis.ProviderCapabilities{
		SupportsSelfHosted: true,
		RequiresAPIKey:     true,
		SupportsRedaction:  false,
		Status:             "active",
	})
}

// RegisterAsOpenAI registers the provider as "openai" (for direct OpenAI use).
func RegisterAsOpenAI(r *codeanalysis.ProviderRegistry) error {
	return r.Register("openai", NewOpenAIProvider, codeanalysis.ProviderCapabilities{
		SupportsSelfHosted: false, // OpenAI SaaS only
		RequiresAPIKey:     true,
		SupportsRedaction:  false,
		Status:             "active",
	})
}

// RegisterAsAzureOpenAI registers the provider as "azure-openai".
func RegisterAsAzureOpenAI(r *codeanalysis.ProviderRegistry) error {
	return r.Register("azure-openai", NewOpenAIProvider, codeanalysis.ProviderCapabilities{
		SupportsSelfHosted: false,
		RequiresAPIKey:     true,
		SupportsRedaction:  false,
		Status:             "active",
	})
}

var _ codeanalysis.CodeAnalysisProvider = (*OpenAIProvider)(nil)