// Package iac provides stubs for Infrastructure-as-Code generators.
// This is a replacement for the deleted integrations/iac package
// that was removed in Phase 0 cleanup.
package iac

import (
	"context"
	"fmt"
)

// ResourceModel holds all resources to be exported as IaC.
type ResourceModel struct {
	Provider     string
	Projects     []ProjectResource
	Environments []EnvironmentResource
	Flags        []FlagResource
	Segments     []SegmentResource
	Webhooks     []WebhookResource
	APIKeys      []APIKeyResource
}

// ProjectResource represents a project in the resource model.
type ProjectResource struct {
	Name string
	Slug string
}

// EnvironmentResource represents an environment in the resource model.
type EnvironmentResource struct {
	ProjectSlug string
	Key         string
	Name        string
	Slug        string
	Color       string
}

// FlagResource represents a feature flag in the resource model.
type FlagResource struct {
	ProjectSlug  string
	Key          string
	Name         string
	FlagType     string
	DefaultValue string
	Environments []FlagEnvironment
}

// FlagEnvironment represents a flag's per-environment state.
type FlagEnvironment struct {
	EnvKey  string
	Enabled bool
}

// SegmentResource represents a segment in the resource model.
type SegmentResource struct {
	ProjectSlug string
	Key         string
	Name        string
	MatchType   string
	Rules       []SegmentCondition
}

// SegmentCondition represents a single rule condition in a segment.
type SegmentCondition struct {
	Attribute string
	Operator  string
	Values    []string
}

// WebhookResource represents a webhook in the resource model.
type WebhookResource struct {
	Name       string
	URL        string
	Enabled    bool
	EventTypes []string
}

// APIKeyResource represents an API key in the resource model.
type APIKeyResource struct {
	EnvKey string
	Role   string
}

// GeneratedFile is a single generated IaC file.
type GeneratedFile struct {
	Path     string `json:"path"`
	Content  string `json:"content"`
	Language string `json:"language"`
}

// Generator defines the interface for an IaC generator.
type Generator interface {
	Name() string
	FileExtension() string
	Generate(ctx context.Context, model ResourceModel) ([]GeneratedFile, error)
}

// GeneratorFactory creates a new Generator instance.
type GeneratorFactory func() Generator

var generators = make(map[string]GeneratorFactory)

// RegisterGenerator registers a named generator factory.
func RegisterGenerator(name string, factory GeneratorFactory) {
	generators[name] = factory
}

// ListGenerators returns all registered generator names.
func ListGenerators() []string {
	names := make([]string, 0, len(generators))
	for name := range generators {
		names = append(names, name)
	}
	return names
}

// NewGenerator creates a new Generator for the named format.
func NewGenerator(name string) (Generator, error) {
	factory, ok := generators[name]
	if !ok {
		return nil, fmt.Errorf("unsupported format: %s", name)
	}
	return factory(), nil
}

// NewTerraformGenerator creates a new Terraform generator.
func NewTerraformGenerator() Generator {
	return &stubGenerator{name: "terraform", ext: ".tf"}
}

// NewPulumiGenerator creates a new Pulumi generator.
func NewPulumiGenerator() Generator {
	return &stubGenerator{name: "pulumi", ext: ".ts"}
}

// NewAnsibleGenerator creates a new Ansible generator.
func NewAnsibleGenerator() Generator {
	return &stubGenerator{name: "ansible", ext: ".yml"}
}

type stubGenerator struct {
	name string
	ext  string
}

func (g *stubGenerator) Name() string {
	return g.name
}

func (g *stubGenerator) FileExtension() string {
	return g.ext
}

func (g *stubGenerator) Generate(_ context.Context, model ResourceModel) ([]GeneratedFile, error) {
	return []GeneratedFile{
		{
			Path:     fmt.Sprintf("featuresignals-%s.%s", g.name, g.ext),
			Content:  "# Generated by FeatureSignals IaC generator (" + g.name + ")\n# Projects: " + fmt.Sprint(len(model.Projects)) + "\n",
			Language: g.name,
		},
	}, nil
}