ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone TEXT,
    ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS phone_otp TEXT,
    ADD COLUMN IF NOT EXISTS phone_otp_expires_at TIMESTAMPTZ;
