#!/usr/bin/env bash
set -euo pipefail

# Checks ALL .go, .ts, .tsx files for copyright headers.
# Skips generated files, vendor, node_modules, .next.
# Exits with error code if any file is missing a header.

ERRORS=0
YEAR=$(date +%Y)

# Go files
while IFS= read -r file; do
    if ! head -2 "$file" | grep -qE "Copyright $YEAR|Copyright 202[0-9]"; then
        if ! head -1 "$file" | grep -q "Code generated by"; then
            echo "❌ Missing copyright: $file"
            ERRORS=$((ERRORS + 1))
        fi
    fi
done < <(find . -name '*.go' -not -path '*/vendor/*' -not -path '*/.git/*' -not -path '*/internal/dagger/*')

# TypeScript files
while IFS= read -r file; do
    if ! head -3 "$file" | grep -qE "Copyright $YEAR|Copyright 202[0-9]"; then
        echo "❌ Missing copyright: $file"
        ERRORS=$((ERRORS + 1))
    fi
done < <(find . -name '*.ts' -o -name '*.tsx' | grep -v node_modules | grep -v .next | grep -v out)

exit $ERRORS
